export interface Offer {
  _id?: string; // Optional, usually generated by MongoDB
  title: string;
  company: string;
  location: string;
  duration: string;
  startDate: string;
  responsibilities: string[];
  profile: string[];
  requiredDocuments: string[];
  notes: string;
  website: string;
  contactEmail: string;

  // Index signature to allow extra dynamic fields, like `strict: false` in Mongoose
  [key: string]: any;
}
